baseURL = "https://heds-lab.com/"
defaultContentLanguage = "en"
languageCode = "en"

title = "Human-centered Educational Data Science Lab"

theme = "gokarna"

# Automatically generate robots.txt
enableRobotsTXT = true

[params]
  footer = "HEDS Lab"
  avatarURL = "/images/HEDS-logo-simple.svg"
  customHeadHTML = '''
    <link rel="stylesheet" href="/css/custom.css">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/site.webmanifest">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">
  '''

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "research"
    name = "Research"
    url = "/research/"
    weight = 2

  [[menu.main]]
    identifier = "people"
    name = "People"
    url = "/people/"
    weight = 3

  [[menu.main]]
    identifier = "contact"
    name = "Get in touch"
    url = "/contact/"
    weight = 4

    # We use feather-icons: https://feathericons.com/
    # pre = "<span data-feather='github'></span>"
